#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend eziuka.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 304605-web-01 100.27.4.79
        server 304605-web-02 37.175.105.48
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
